version: '3'
services:
  teamcity_db:
    image: mysql:${SQL_VERSION}
    environment:
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      SQL_DATABASE: ${SQL_DATABASE}
    volumes:
      - ${SQL_VOLUME}:/var/lib/mysql
    restart: ${RESTART_POLICY}
  teamcity_agent1:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://teamcity_server:8111
      - AGENT_NAME=${TEAMCITY_AGENT_NAME_1}
    restart: ${RESTART_POLICY}
    links:
      - teamcity_server
    depends_on:
      - teamcity_server
  teamcity_agent2:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://teamcity_server:8111
      - AGENT_NAME=${TEAMCITY_AGENT_NAME_2}
    restart: ${RESTART_POLICY}
    links:
      - teamcity_server
    depends_on:
      - teamcity_server
  teamcity_server:
    image: jetbrains/teamcity-server
    ports:
      - ${TEAMCITY_PORT}:8111
    restart: ${RESTART_POLICY}
    volumes:
      - ${TEAMCITY_VOLUME}:/opt/teamcity
      - ${TEAMCITY_SERVER_VOLUME}:/opt/teamcity_server
    depends_on:
      - teamcity_db
  phpmyadmin:
    image: phpmyadmin
    restart: ${RESTART_POLICY_PHPMYADMIN}
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
